### ISSUE TITLE
Physical/Logical path issue

### ISSUE THREAD

**Issue by yunoJ** [yunoJ/Coq#1]
Machine: ubuntu 18.04
Running on: coqide
coq version: 8.9.0
installed with: opam

I have trouble starting on the second chapter induction.v.

Error: Cannot find a physical path bound to logical path matching suffix
<> and prefix LF.

This message is displayed after compilation. My _CoqProject file has one line "-Q . LF". My coqide's preferences points to _CoqProject as expected.

The line creating above error is: From LF Require Export Basics. (I have compiled Basics.v and have Basics.vo file in the same directory)

I have searched the internet and issued on coq github and still have no answer.

This may not be an appropriate question for you but this has been agonizing me for almost a week now. Hope you can help me on this problem.

Thank you in advance.

**Comment by jeehoonkang** [comment]
I'd like you to just avoid this issue by copying-and-pasting all the contents of software foundations, and starting from there.

**Comment by yunoJ** [comment]
I was doing just that but I guess I should download the files again then. Thank you for the prompt reply.

**Comment by jeehoonkang** [comment]
Is this issue resolved?

**Comment by yunoJ** [comment]
Yes there was a minor problem with the instruction on opam website. 
I will close this issue as it is resolved.
