### ISSUE TITLE
Lists.v example problem

### ISSUE THREAD

**Issue by yunoJ** [yunoJ/Coq#2]
Last week has been midterm week in my school so I couldn't spend much time on studies that you told me to do. I am sorry about that.

I started studying lists in coq and got stuck on an example problem.

The example asks me to define fixpoint remove_all. Below is the given format.

`Fixpoint remove_all  (v:nat) (s:bag) : bag :=`

this should remove all elements in s that is equal to v.  (nat is abbreviation for natural number and bag is defined as natural number list)

Here is what I got so far:

```
Fixpoint remove_all (v:nat) (s:bag) : bag :=
  match s with 
  | nil => nil
  | h :: t => if eqb h v then t v t else match t with
              | nil => nil
              | h1 :: t1 => if eqb h1 v then h :: remove_all v t1 else h :: remove_all v t
              end
end.
```

My code first compares the head of the list with v and if they are not the same, it moves on and appends the tail with all elements equal to v removed. For example, if a list is constructed as [h; h1; t1], h is compared with v and if they are the same, [h1; t1] is returned. If they are not the same, h1 is compared with v, appending t with h --[h; t1]-- when same and moving on to testing the rest of the list when not. 

The problem is when 5's are to be removed from [1; 2; 5; 5; 3], the resulting list will be [3] when it should be [1; 2; 3]. How can I concatenate the list  with the one in the previous recursion?

Sorry for the long question.

Thank you in advance!

**Comment by jeehoonkang** [comment]
Try something like:

```coq
Fixpoint remove_all (v:nat) (s:bag) : bag :=
  match s with 
  | nil => nil
  | h :: t => if eqb h v then remove_all t else [...]
  end.
```

**Comment by yunoJ** [comment]
Thank you,

Here's the fixed code:

```
Fixpoint remove_all (v:nat) (s:bag) : bag :=
  match s with 
  | nil => nil
  | h :: t => if eqb h v then remove_all v t else match t with
              | nil => nil
              | h1 :: t1 => if eqb h1 v then h :: remove_all v t1 else h :: remove_all v t
              end
end.
```
Does the `remove_all v t` in line  `| h :: t => if eqb h v then remove_all v t else match t with ` automatically appends the result of `remove_all v t` to h?

**Comment by jeehoonkang** [comment]
Instead of answering your question directly, I'd like to say there's no need to use `match` twice.

**Comment by yunoJ** [comment]
Fixed it with
```
Fixpoint remove_all (v:nat) (s:bag) : bag :=
  match s with 
  | nil => nil
  | h :: t => if eqb h v then remove_all v t else h :: remove_all v t
end.
```
Thank you for the support!

I will close this issue as it is resolved.
