### ISSUE TITLE
Poly.v question.

### ISSUE THREAD

**Issue by yunoJ** [yunoJ/Coq#3]
Hello professor,

I hope that you are having a good time with your family for 어린이날. 

I have to interrupt you though for a problem with poly.v in coq. 

It's about inductively defined types and here goes. 

```
Inductive mumble : Type :=
  | a
  | b (x : mumble) (y : nat)
  | c.

Inductive grumble (X:Type) : Type :=
  | d (m : mumble)
  | e (x : X).
```
Above is the given code and I have to decide whether given statements are well-typed elements of [grumble X]. 

I did `Check d bool (b a 5).`  and there was no error even though `bool` is another `Type` just like `mumble` and does not belong to `mumble`. What I understood from the reading materials is `m` in `d (m : mumble)` should belong to `mumble`. Since `b a 5` is an element of `mumble` and `bool` is not, shouldn't the line be `Check d (b a 5)` to not raise an error?

**Comment by jeehoonkang** [comment]
bool is X

**Comment by yunoJ** [comment]
I guess I understood it in incorrectly. Thank you professor!
