### ISSUE TITLE
Church numerals in poly.v

### ISSUE THREAD

**Issue by yunoJ** [yunoJ/Coq#4]
Defining Church numerals in the extra examples section of polymorphism chapter isn't working out as expected. 
 
Below is give code: 
```Coq
Definition cnat := forall X : Type, (X -> X) -> X -> X.

Definition zero : cnat :=
  fun (X : Type) (f : X -> X) (x : X) => x.

Definition one : cnat :=
  fun (X : Type) (f : X -> X) (x : X) => f x.

Definition two : cnat :=
  fun (X : Type) (f : X -> X) (x : X) => f (f x).
```
and this isn't that hard to understand. But I am asked to define successor(1 -> 2, 2->3, so on) and below is my code.

```Coq
Definition succ (n : cnat) : cnat :=
  fun X f x => X f (f x).
```
The way I intended my definition to be read is "infer from the input `cnat` type, function and value and use the aforesaid attributes to yield f (f (x)) of type X." The problem is that I can't figure out how to take `n` into account. I guess this should work for ```Example succ_2 : succ one = two.``` but I am pretty sure that it will fail for other cases. Please help...

**Comment by jeehoonkang** [comment]
- `X` is not a function.   So `X f (f x)` is strange.
- You have to somehow utilize `n` in your recursive definition.

**Comment by jeehoonkang** [comment]
Hint: you wanna have `(n+1) f x = f  (n f x)`.

**Comment by yunoJ** [comment]
Resolved it with
```Coq
Definition succ (n: cnat) : cnat :=
  fun X f x => f (n X f x).
```
Which should be read as " `succ` is a function that takes `cnat` as input and outputs `cnat`, and f(x) means applying the same function to `n` of type `cnat`." thus changing `zero` to `one` and so on.

However, I understood that this `succ` is a function that given a function f(x) of type X, yields f( n f x). Does that mean `succ` has two inputs? `(n : cnat)` and `f x`?

**Comment by jeehoonkang** [comment]
Yeah.  Cnat is a function

**Comment by yunoJ** [comment]
Alright, closing the issue as it is resolved.
